### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by albertossilva**

### CODE REVIEW

**Comment by albertossilva** [comment]
The main reason for this upgrade is `npm audit`. Now it has 0 vulnerabilties

**Comment by njzjz** [comment]
Feels good to me. Maybe I can use it instead the original one.

**Comment by njzjz** [comment]
Using your code with webpack, I catch the error `Uncaught ReferenceError: regeneratorRuntime is not defined`. What's wrong?

**Comment by njzjz** [comment]
> Using your code with webpack, I catch the error `Uncaught ReferenceError: regeneratorRuntime is not defined`. What's wrong?

The problem is fixed by installing and importing [regenerator-runtime](https://www.npmjs.com/package/regenerator-runtime).

**Comment by albertossilva** [comment]
So... @njzjz, should I install and add this dependency to my branch as well?

**Comment by njzjz** [comment]
> So... @njzjz, should I install and add this dependency to my branch as well?

I add the following before import jsnetworkx:

```js
global.regeneratorRuntime = require("regenerator-runtime");
```

and it works.

**Comment by albertossilva** [comment]
So.. it makes sense to add on the documentation, that this library is
required when used in webpack.

**Comment by albertossilva** [comment]
Won't do

**Pull request closed without merging**
